### ISSUE TITLE
OptiFabric doesn't work

### ISSUE THREAD

**Issue by AFinalWord** [Trainguy9512/trainguys-animation-overhaul#11]
I wanted to play this with the fresh animations resource pack, but in order to use that I need OptiFine, so I tried using OptiFabric, but OptiFabric wouldn't work, did I do something wrong or is this just a mod bug / glitch / problem?
![image](https://user-images.githubusercontent.com/94770604/144873444-c2addcab-617c-4e49-8c5e-7ea5cda2c811.png)
![image](https://user-images.githubusercontent.com/94770604/144873582-b14e26c6-b5e2-4137-a037-81c2217d44e9.png)

**Comment by Mw3y** [comment]
Same here

**Comment by Mw3y** [comment]
Here's the crash report:
`
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:601)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:173)
	at net.minecraft.class_128.method_24305(class_128.java:343)
	at net.minecraft.client.main.Main.main(Main.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method notifyNearbyEntitiesWithSongName(Lnet/minecraft/class_3414;Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in animationoverhaul.mixins.json:MixinLevelRenderer from mod animation_overhaul failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap trainguys-animation-overhaul-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more
`

**Comment by SUPERN00Bthefirst** [comment]
I would like to recommend that you re-read the FAQ, Optifine, and Optifabric are not currently supported.

**Comment by Vextrove** [comment]
Optifabric is not supported.
Nowadays there isn't really a reason to still use Optifine or Optifabric when there are better alternatives for most of Optifine's features:
https://lambdaurora.dev/optifine_alternatives/

**Comment by Vexalus** [comment]
@AFinalWord You should probably close this.

**Comment by zuliwa** [comment]
> Optifabric is not supported. Nowadays there isn't really a reason to still use Optifine or Optifabric when there are better alternatives for most of Optifine's features: https://lambdaurora.dev/optifine_alternatives/

What about shaders and certain resource packs?
Some shaders don't work with iris, and I've yet to find a mod that makes the resource pack I use work without optifine

**Comment by souls-are-tasty** [comment]
I use optifabric and I was fine
